name: TDOE
description: TDOE的日常
timezone: Asia/Shanghai
logo: "/assets/images/brand.png"
attribution: heweather.com
github: https://github.com/heweather
webmaster_verifications:
  google: 5mJlHKIddhky6OQT5qb7M2Uit2yzg4WGwG7JBxWQ6Cw
  bing: EDFBFE217D2B905D82BE1D5A1BC9AB28

defaults:
- scope:
    path: "pages"
    type: "pages"
  values:
    layout: "html"
- scope:
    path: "_posts"
    type: "posts"
  values:
    layout: "post"
    permalink: "/post/:slug"
sass:
  sass_dir: _sass
  style: compressed

exclude:
- .idea
- .git
- .gitignore
- .sass-cache
- .jekyll-cache
- README.md

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
